import { RotateCcw, ShieldCheck, Truck, Zap } from 'lucide-react';
import type { Category, HeroSlide, Product, TrustItem } from './types';

export const CATEGORIES: Category[] = [
    { id: 0, label: 'All Parts', count: 5620 },
    { id: 1, label: 'Engine Parts', count: 1240 },
    { id: 2, label: 'Brake Systems', count: 890 },
    { id: 3, label: 'Suspension', count: 620 },
    { id: 4, label: 'Electrical', count: 1050 },
    { id: 5, label: 'Filters & Fluids', count: 430 },
    { id: 6, label: 'Body & Exterior', count: 780 },
    { id: 7, label: 'Transmission', count: 340 },
    { id: 8, label: 'Exhaust Systems', count: 260 },
];

export const PRODUCTS: Product[] = [
    {
        id: 1,
        name: 'High-Performance Oil Filter',
        brand: 'Bosch',
        price: 24.99,
        originalPrice: 34.99,
        rating: 4.8,
        reviews: 312,
        tag: 'SALE',
        category: 'Filters & Fluids',
    },
    {
        id: 2,
        name: 'Ceramic Brake Pads Set',
        brand: 'Brembo',
        price: 89.95,
        originalPrice: null,
        rating: 4.9,
        reviews: 528,
        tag: 'BESTSELLER',
        category: 'Brake Systems',
    },
    {
        id: 3,
        name: 'LED Headlight Assembly',
        brand: 'Philips',
        price: 149.0,
        originalPrice: 199.0,
        rating: 4.7,
        reviews: 214,
        tag: 'SALE',
        category: 'Electrical',
    },
    {
        id: 4,
        name: 'Timing Belt Kit Complete',
        brand: 'Gates',
        price: 64.5,
        originalPrice: null,
        rating: 4.6,
        reviews: 187,
        tag: 'NEW',
        category: 'Engine Parts',
    },
    {
        id: 5,
        name: 'Shock Absorber Rear Pair',
        brand: 'KYB',
        price: 129.99,
        originalPrice: 159.99,
        rating: 4.8,
        reviews: 95,
        tag: 'SALE',
        category: 'Suspension',
    },
    {
        id: 6,
        name: 'Air Filter High-Flow',
        brand: 'K&N',
        price: 54.99,
        originalPrice: null,
        rating: 4.9,
        reviews: 644,
        tag: 'BESTSELLER',
        category: 'Filters & Fluids',
    },
    {
        id: 7,
        name: 'Alternator 12V 140A',
        brand: 'Denso',
        price: 189.0,
        originalPrice: 229.0,
        rating: 4.7,
        reviews: 73,
        tag: null,
        category: 'Electrical',
    },
    {
        id: 8,
        name: 'Spark Plugs — Set of 4',
        brand: 'NGK',
        price: 32.4,
        originalPrice: null,
        rating: 4.9,
        reviews: 901,
        tag: 'NEW',
        category: 'Engine Parts',
    },
];

export const HERO_SLIDES: HeroSlide[] = [
    {
        id: 0,
        eyebrow: 'Up to 40% off Brake Systems',
        title: 'Brake Parts Deals\nUp To 40% Off',
        sub: 'Premium ceramic pads, rotors & calipers from Brembo, ATE & Wagner. Ships today.',
        cta: 'Shop Brake Deals',
        ctaAlt: 'Browse All Parts',
        chips: ['Brake Pads', 'Rotors', 'Calipers', 'Brake Fluid'],
        slideLabel: 'Brake Deals',
        featured: {
            name: 'Ceramic Brake Pads Set',
            brand: 'Brembo',
            price: 89.95,
            originalPrice: 149.95,
            rating: 4.9,
            reviews: 528,
            inStock: true,
            fitment: 'Fits BMW, Audi & VW models',
            discountPct: 40,
        },
    },
    {
        id: 1,
        eyebrow: 'New Arrivals — Engine Parts',
        title: 'Top Engine Parts,\nReady To Ship',
        sub: 'Timing belts, gaskets & rebuild kits. OEM-quality at aftermarket prices.',
        cta: 'Shop Engine Parts',
        ctaAlt: "View Today's Deals",
        chips: ['Timing Belts', 'Oil Filters', 'Gaskets', 'Spark Plugs'],
        slideLabel: 'Engine Parts',
        featured: {
            name: 'Timing Belt Kit Complete',
            brand: 'Gates',
            price: 64.5,
            originalPrice: 89.99,
            rating: 4.6,
            reviews: 187,
            inStock: true,
            fitment: 'Fits 180+ vehicle models',
            discountPct: 28,
        },
    },
    {
        id: 2,
        eyebrow: 'LED Lighting Collection',
        title: 'Premium LED Parts,\nEasy Plug-and-Play',
        sub: 'Next-gen LED assemblies for every make and model. 2-year warranty included.',
        cta: 'Shop LED Lighting',
        ctaAlt: 'Check Fitment',
        chips: ['Headlights', 'Tail Lights', 'Fog Lights', 'Bulbs'],
        slideLabel: 'LED Lighting',
        featured: {
            name: 'LED Headlight Assembly',
            brand: 'Philips',
            price: 149.0,
            originalPrice: 199.0,
            rating: 4.7,
            reviews: 214,
            inStock: true,
            fitment: 'Fits Toyota, Honda & Ford',
            discountPct: 25,
        },
    },
];

export const TRUST_ITEMS: TrustItem[] = [
    { icon: Truck, label: 'Free Shipping', desc: 'On orders over $75' },
    {
        icon: ShieldCheck,
        label: 'Genuine Parts',
        desc: 'OEM & OE-quality only',
    },
    { icon: RotateCcw, label: '60-Day Returns', desc: 'No questions asked' },
    {
        icon: Zap,
        label: 'Fast Dispatch',
        desc: 'Same-day on orders before 2 PM',
    },
];
